//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_project {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Final_project.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Максимальная длина адреса должна быть менее 100 символов!.
        /// </summary>
        internal static string InvalidMaxLengthAdress {
            get {
                return ResourceManager.GetString("InvalidMaxLengthAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Максимальная длина Имени должна быть менее 50 символов!.
        /// </summary>
        internal static string InvalidMaxLengthName {
            get {
                return ResourceManager.GetString("InvalidMaxLengthName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Максимальная длина номера должна быть менее 12 символов!.
        /// </summary>
        internal static string InvalidMaxLengthPhone {
            get {
                return ResourceManager.GetString("InvalidMaxLengthPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Минимальная длина адреса должна быть более 10 символов!.
        /// </summary>
        internal static string InvalidMinLengthAdress {
            get {
                return ResourceManager.GetString("InvalidMinLengthAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Минимальная длина Имени должна быть более 2 символов!.
        /// </summary>
        internal static string InvalidMinLengthName {
            get {
                return ResourceManager.GetString("InvalidMinLengthName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Минимальная длина номера должна быть более 5 символов!.
        /// </summary>
        internal static string InvalidMinLengthPhone {
            get {
                return ResourceManager.GetString("InvalidMinLengthPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес не может быть равен нулю.
        /// </summary>
        internal static string InvalidNullAdress {
            get {
                return ResourceManager.GetString("InvalidNullAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя не может быть равно нулю.
        /// </summary>
        internal static string InvalidNullName {
            get {
                return ResourceManager.GetString("InvalidNullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон не может быть равен нулю.
        /// </summary>
        internal static string InvalidNullPhone {
            get {
                return ResourceManager.GetString("InvalidNullPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некоректный номер.
        /// </summary>
        internal static string InvalidNumberLengthPhone {
            get {
                return ResourceManager.GetString("InvalidNumberLengthPhone", resourceCulture);
            }
        }
        internal static string InvalidPhone
        {
            get
            {
                return ResourceManager.GetString("InvalidPhone", resourceCulture);
            }
        }

        internal static string InvalidNullEmail
        {
            get
            {
                return ResourceManager.GetString("InvalidNullEmail", resourceCulture);
            }
        }

        internal static string InvalidEmail
        {
            get
            {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
    }
}
